services:

  # Container 1: Reverse Proxy (HTTPS)
  nginx:
    image: nginx:1.25.5-alpine
    depends_on: [orthanc]
    restart: unless-stopped
    ports: ["80:80", "443:443", "104:104"]
    volumes:
      - ./tls:/etc/nginx/tls
      - ./default.conf:/etc/nginx/conf.d/default.conf


  # Container 2: Viewer
  ohif:
    image: orthancteam/ohif-v3:24.5.0
    #volumes:
      #- ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped

  #Container 3: ORTHANC PACS (DISME e DICOMweb)
  orthanc:
    image: orthancteam/orthanc:24.5.0
    restart: unless-stopped
    volumes:
      - ./tmp/orthancADM-logs-docker:/logs
      - ./orthancADM.json:/etc/orthanc/orthanc.json:ro
    environment:
      # Console Logs
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      # Logs
      LOGDIR: "/logs"
      ORTHANC__DE_IDENTIFY_LOGS: "false"

    # Activate a healthcheck service
    labels:
      - "autoheal=true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/probes/test-aliveness.py --user=healthcheck --pwd=${HEALTHCHECK_PASSWORD}"
        ]
      start_period: 10s
      retries: 2
      interval: 3s
      timeout: 2s

  # Container 6: Supervision
  # Activate an AutoHeal service
  # If healthcheck is false or unhealth restarts the instance
  # Uses the Unix Domain Socket to communicate.
  autoheal:
    image: willfarrell/autoheal:1.2.0
    tty: true
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nginx-tls:
  orthanc-logs:
