services:

  # Container 1: Reverse Proxy (HTTPS)
  nginx:
    image: nginx:1.25.5-alpine
    depends_on: [ orthanc ]
    restart: unless-stopped
    ports: [ "443:443" ]
    volumes:
      - ./tls/crt.pem:/etc/nginx/tls/crt.pem
      - ./tls/key.pem:/etc/nginx/tls/key.pem
      - ./default.conf:/etc/nginx/conf.d/default.conf

  # Container 2: Viewer
  ohif:
    image: orthancteam/ohif-v3:24.5.1
    #volumes:
    #- ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped

  #Container 3: ORTHANC PACS (DICOMweb & GUI)
  orthanc:
    image: orthancteam/orthanc:24.5.1
    restart: unless-stopped
    volumes:
      - ./tmp/orthancDICOMweb-logs-docker:/logs
      - ./orthancDICOMweb.json:/etc/orthanc/orthanc.json:ro
    environment:
      # Console Logs
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      # Logs
      LOGDIR: "/logs"
      ORTHANC__DE_IDENTIFY_LOGS: "false"

    # Activate a healthcheck service
    labels:
      - "autoheal=true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/probes/test-aliveness.py --user=healthcheck --pwd=${HEALTHCHECK_PASSWORD}"
        ]
      start_period: 10s
      retries: 2
      interval: 3s
      timeout: 2s

  #Container 4: ORTHANC PACS (DISME)
  orthanc-dicom:
    image: orthancteam/orthanc:24.5.1
    restart: unless-stopped
    ports:
      - "2762:4242"
    volumes:
      - ./tmp/orthancDICOM-logs-docker:/logs
      - ./orthancDICOM.json:/etc/orthanc/orthanc.json:ro
      - ./tls:/tls:ro
    environment:
      # Console Logs
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      # Logs
      LOGDIR: "/logs"
      ORTHANC__DE_IDENTIFY_LOGS: "false"

    # Activate a healthcheck service
    labels:
      - "autoheal=true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/probes/test-aliveness.py --user=healthcheck --pwd=${HEALTHCHECK_PASSWORD} > ./logs/healthcheck.log 2>&1"
        ]
      start_period: 10s
      retries: 2
      interval: 3s
      timeout: 2s

  # Container 5: Supervision
  # Activate an AutoHeal service
  # If healthcheck is false or unhealth restarts the instance
  # Uses the Unix Domain Socket to communicate.
  autoheal:
    image: willfarrell/autoheal:1.2.0
    tty: true
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nginx-tls:
  orthanc-logs:
